### ISSUE TITLE
Direct replies to comments (and to replies)

### ISSUE THREAD

**Issue by joshl129** [peer/mind#158] opened 2016-08-30 22:04 UTC
I've been using this platform a bit just now and think that it would be very helpful in organizing discussions to be able to directly reply to comments, to those replies, etc. (they would show up Reddit-style, perhaps organized by number of upvotes).

**Comment by mitar** [comment] 2016-08-31 00:14
A duplicate of #28.

See discussion there. My personal position is that I would first like to try few other ideas. I know that for now commenting is pretty simple.

**Closed** 2016-08-31 00:14 UTC
Labels: duplicate
